### ISSUE TITLE
Can't mount writable /nix/store overlay

### ISSUE THREAD

**Issue by onsails** [astro/microvm.nix#210] opened 2024-03-05 20:11 UTC
I'm trying to mount a writeable overlay with exact options suggested by [docs](https://astro.github.io/microvm.nix/shares.html#writable-nixstore-overlay):

```
        microvm = {
            mem = 16 * 1024;
            vcpu = 16;

            hypervisor = "qemu";
            interfaces = [{
              type = "tap";
              id = "vm-1";
              mac = "02:00:00:01:01:01";
            }];

            writableStoreOverlay = "/nix/.rw-store";

            volumes = [{
              image = "nix-store-overlay.img";
              mountPoint = config.microvm.writableStoreOverlay;
              size = 2048;
            }];
          };
        };
```

It fails to mount overlay with the following log:

```
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]:          Mounting /sysroot...
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]:          Starting Rule-based Manager for Device Events and Files...
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Mounted /sysroot.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Reached target Initrd Root File System.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]:          Starting Mountpoints Configured in the Real Root...
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Started Journal Service.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]:          Starting Create Volatile Files and Directories...
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Found device /dev/disk/by-label/nix-store.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Found device /dev/vdb.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Started Rule-based Manager for Device Events and Files.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Finished Load Kernel Modules.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Finished Coldplug All udev Devices.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Finished Create Volatile Files and Directories.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Finished Mountpoints Configured in the Real Root.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]:          Starting File System Check on /dev/vdb...
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]:          Starting Apply Kernel Variables...
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]:          Starting Virtual Console Setup...
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Finished Apply Kernel Variables.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Finished File System Check on /dev/vdb.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Finished Virtual Console Setup.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Reached target System Initialization.
Mar 05 20:05:43 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Reached target Basic System.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]:          Mounting /sysroot/nix/.ro-store...
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]:          Mounting /sysroot/nix/.rw-store...
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Mounted /sysroot/nix/.ro-store.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Mounted /sysroot/nix/.rw-store.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]:          Starting rw-store.service...
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Finished rw-store.service.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]:          Mounting /sysroot/nix/store...
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [FAILED] Failed to mount /sysroot/nix/store.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: See 'systemctl status sysroot-nix-store.mount' for details.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [DEPEND] Dependency failed for Initrd File Systems.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped Dispatch Password Requests to Console Directory Watch.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]:          Starting Cleaning Up and Shutting Down Daemons...
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped target Basic System.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped target System Initialization.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Started Emergency Shell.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Reached target Emergency Mode.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped target Emergency Mode.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped target Initrd Root Device.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped target Path Units.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped target Slice Units.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped target Socket Units.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped target Swaps.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped target Timer Units.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped Create List of Static Device Nodes.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]:          Starting rw-store.service...
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped Apply Kernel Variables.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped Create Volatile Files and Directories.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped target Local File Systems.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped target Preparation for Local File Systems.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped Coldplug All udev Devices.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]:          Stopping Rule-based Manager for Device Events and Files...
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped Virtual Console Setup.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped Emergency Shell.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Finished rw-store.service.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Finished Cleaning Up and Shutting Down Daemons.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]:          Mounting /sysroot/nix/store...
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [FAILED] Failed to mount /sysroot/nix/store.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: See 'systemctl status sysroot-nix-store.mount' for details.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [DEPEND] Dependency failed for Initrd File Systems.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Started Emergency Shell.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Reached target Emergency Mode.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped Rule-based Manager for Device Events and Files.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Closed udev Control Socket.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Closed udev Kernel Socket.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]:          Starting Cleanup udev Database...
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Stopped Create Static Device Nodes in /dev.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Finished Cleanup udev Database.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [  OK  ] Reached target Switch Root.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]:          Starting Switch Root...
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: [FAILED] Failed to start Switch Root.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: See 'systemctl status initrd-switch-root.service' for details.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: You are in emergency mode. After logging in, type "journalctl -xb" to view
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: system logs, "systemctl reboot" to reboot, or "exit"
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: to continue bootup.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]:
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: Cannot open access to console, the root account is locked.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: See sulogin(8) man page for more details.
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]:
Mar 05 20:05:44 my-github-runner microvm@nix-runner-1[587697]: Press Enter to continue.
```

Similar failure happens on cloud-hypervisor and crosvm, I can share logs if it matters.
VM is defined declaratively via nixosModule.

Not sure if it's possible to connect to VM console to look at exact systemd logs, couldn't find a way to do so considering microvms are headless.

**Comment by onsails** [comment] 2024-03-05 21:32
It started working after I changed `image = "nix-store-overlay.img"` to `image = "nix-store-overlay1.img"`. 
Apparently I when I launched my first microvm I used the same name with less size and it's now being reused. Shouldn't we add an option to resize image if it's less than size required by a configuration?

**Comment by onsails** [comment] 2024-03-05 21:39
Hotfixed with:

```
systemd.services = {
  rm-image = {
      serviceConfig = {
        Type = "oneshot";
        ExecStart = pkgs.writeScript "rm-image" ''
          #!${pkgs.runtimeShell}
          rm /var/lib/microvms/nix-runner-1/nix-store-overlay.img
        '';
      };
    };

    "microvm@${name}" = {
      after = [ "rm-image.service" ];
      requires = [ "rm-image.service" ];
    };
};
```

**Comment by astro** [comment] 2024-03-06 19:32
Duplicate of #134

**Closed by astro** 2024-03-06 19:32 UTC
